// eslint-disable-next-line @typescript-eslint/triple-slash-reference
/// <reference path=".snaplet/snaplet.d.ts" />
// This config was generated by Snaplet make sure to check it over before using it.
import { copycat, faker } from "@snaplet/copycat";
import { defineConfig } from "snaplet";
copycat.setHashKey("n1ZR7BYaPN6RnpCf");
export default defineConfig({
  generate: {
    plan({ snaplet }) {},
  },
  transform: {},
});
